services:

    markdown:
        class: Andchir\MarkdownBundle\Service\MarkdownService
        arguments: ['@service_container', '@logger']
        public: true
        autowire: true

    Andchir\MarkdownBundle\Twig\AppExtension:
        tags: ['twig.extension']
        arguments: ['@service_container']